security:

  providers:
    in_memory:
      memory:
        users:
          - { name: admin@mail.com, password: admin, roles: 'ROLE_ADMIN' }

  encoders:
    Symfony\Component\Security\Core\User\User: plaintext

  firewalls:
    main:
      pattern: ^/
      anonymous: ~
      form_login:
        login_path: /authorization
        check_path: /authorization_check
      logout:
        path: /logout
        target: /
      provider: in_memory

  access_control:
    - { path: ^/authorization, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    #- { path: ^/admin, roles: ROLE_ADMIN }
